/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




namespace AceGen.Todo.Data;

public class TodoData : AbstractTodoData, ITodoData {
	
	public TodoData(
		string? id, 
		string? description, 
		bool? done, 
		DateTime? createdDateTime, 
		DateTime? updatedDateTime, 
		string? categoryId, 
		string uuid
	) : base(id, description, done, createdDateTime, updatedDateTime, categoryId, uuid) {
	}

	public TodoData( string uuid ) : base(uuid) {
	}

	override public void MigrateLegacyData(String json) {
	}

	public static ITodoData GenerateTestData() {
		Random random = new Random();
		ITodoData testData = (ITodoData) new AceGen.Todo.Models.TodoModel();
		testData.Id = RandomString(random);
		testData.Description = RandomString(random);
		testData.Done = RandomBool(random);
		testData.CreatedDateTime = RandomBool(random) ? DateTime.Now.AddMinutes(random.Next(60)) : DateTime.Now.AddMinutes(-1*random.Next(60)) ;;
		testData.UpdatedDateTime = RandomBool(random) ? DateTime.Now.AddMinutes(random.Next(60)) : DateTime.Now.AddMinutes(-1*random.Next(60)) ;;
		testData.CategoryId = RandomString(random);
		return testData;
	}
	
	private static String RandomString(Random random) {
		String chars = "aaaaaaabcdeeeeeeeffffghiiiiiiijkllllllmmmmnnnnnnnooooooooopqrstttuuuuuuuvxyz";
		int length = random.Next(20) + 5;
		return new string(Enumerable.Repeat(chars, length).Select(s => s[random.Next(s.Length)]).ToArray());
	}
	
	private static bool RandomBool(Random random) {
		return random.Next() > (Int32.MaxValue / 2);
	}
	
	private static float RandomFloat(Random random) {
	    double mantissa = (random.NextDouble() * 2.0) - 1.0;
	    double exponent = Math.Pow(2.0, random.Next(-126, 128));
	    return (float)(mantissa * exponent);
	}
	
	
}



/******* S.D.G. *******/



